version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pulpo-postgres
    environment:
      POSTGRES_DB: pulpo
      POSTGRES_USER: pulpo
      POSTGRES_PASSWORD: pulpo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pulpo -d pulpo"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pulpo-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: pulpo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pulpo-network

  # Ollama LLM
  ollama:
    image: ollama/ollama:latest
    container_name: pulpo-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - pulpo-network

  # RAG Service
  rag:
    build:
      context: .
      dockerfile: Dockerfile.rag
    container_name: pulpo-rag
    ports:
      - "8007:8007"
    environment:
      - DATABASE_URL=postgresql://pulpo:pulpo@postgres:5432/pulpo
      - REDIS_URL=redis://redis:6379
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      ollama:
        condition: service_healthy
    volumes:
      - ./services:/app/services
      - ./shared:/app/shared
      - ./utils:/app/utils
    networks:
      - pulpo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8007/rag/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Orchestrator Service
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.orchestrator
    container_name: pulpo-orchestrator
    ports:
      - "8005:8005"
    environment:
      - DATABASE_URL=postgresql://pulpo:pulpo@postgres:5432/pulpo
      - REDIS_URL=redis://redis:6379
      - RAG_URL=http://rag:8007
      - ACTIONS_URL=http://actions:8006
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rag:
        condition: service_healthy
    volumes:
      - ./services:/app/services
      - ./shared:/app/shared
      - ./utils:/app/utils
    networks:
      - pulpo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Actions Service
  actions:
    build:
      context: .
      dockerfile: Dockerfile.actions
    container_name: pulpo-actions
    ports:
      - "8006:8006"
    environment:
      - DATABASE_URL=postgresql://pulpo:pulpo@postgres:5432/pulpo
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./services:/app/services
      - ./shared:/app/shared
      - ./utils:/app/utils
    networks:
      - pulpo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8006/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # n8n Workflow Engine
  n8n:
    image: n8nio/n8n:latest
    container_name: pulpo-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Argentina/Buenos_Aires
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n:/home/node/.n8n/custom
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      orchestrator:
        condition: service_healthy
      actions:
        condition: service_healthy
      rag:
        condition: service_healthy
    networks:
      - pulpo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:
  ollama_data:
  n8n_data:

networks:
  pulpo-network:
    driver: bridge
    name: pulpo-network
