# Tool Manifest - Vertical: Servicios (Peluquerías, Spas, etc.)
# Versión: v1
# Última actualización: 2025-10-09

workspace_id: null  # Default manifest (se puede override por workspace en DB)
vertical: "servicios"
version: "v1"

tools:
  # ==========================================
  # READ TOOLS - Consulta de información
  # ==========================================

  - name: "get_available_services"
    description: |
      Lista todos los servicios disponibles con sus precios y duraciones.
      Admite filtro opcional por texto (ej: "corte", "color", "manicura").
      Úsalo cuando el cliente pregunte por servicios, precios o duración.
    args_schema:
      type: object
      properties:
        workspace_id:
          type: string
          description: "ID del workspace (requerido por MCP)"
        category:
          type: string
          description: "Filtro de búsqueda opcional por categoría (ej: 'hair', 'nails')"
        q:
          type: string
          description: "Búsqueda por texto en nombre del servicio (opcional)"
      required: ["workspace_id"]
      additionalProperties: false
    requires_slots: []
    scopes: ["read"]
    tier_required: "basic"
    rate_limit_per_min: 60
    cost_tokens: 50
    timeout_ms: 3000

  - name: "check_service_availability"
    description: |
      Consulta disponibilidad de horarios para un servicio específico.
      Requiere: fecha, tipo de servicio y opcionalmente profesional.
      Devuelve slots disponibles (ej: ["10:00", "11:00", "14:00"]).
      IMPORTANTE: Llamar siempre ANTES de book_appointment.
    args_schema:
      type: object
      properties:
        workspace_id:
          type: string
          description: "ID del workspace (requerido por MCP)"
        service_type:
          type: string
          description: "Nombre del servicio (ej: 'Corte de Cabello')"
        date_str:
          type: string
          format: date
          description: "Fecha en formato YYYY-MM-DD"
        staff_id:
          type: string
          description: "ID del profesional (opcional)"
        duration_min:
          type: integer
          minimum: 15
          description: "Duración estimada en minutos (opcional)"
      required: ["workspace_id", "service_type", "date_str"]
      additionalProperties: false
    requires_slots: ["service_type", "preferred_date"]
    scopes: ["read"]
    tier_required: "basic"
    rate_limit_per_min: 30
    cost_tokens: 100
    timeout_ms: 5000

  - name: "get_service_packages"
    description: |
      Obtiene paquetes especiales o combos de servicios disponibles.
      Útil cuando el cliente pregunte por paquetes, promociones combinadas o combos.
    args_schema:
      type: object
      properties:
        workspace_id:
          type: string
          description: "ID del workspace (requerido por MCP)"
      required: ["workspace_id"]
      additionalProperties: false
    requires_slots: []
    scopes: ["read"]
    tier_required: "basic"
    rate_limit_per_min: 60
    cost_tokens: 50
    timeout_ms: 3000

  - name: "get_active_promotions"
    description: |
      Lista las promociones activas vigentes.
      Úsalo cuando el cliente pregunte por descuentos u ofertas especiales.
    args_schema:
      type: object
      properties:
        workspace_id:
          type: string
          description: "ID del workspace (requerido por MCP)"
        check_date:
          type: string
          format: date
          description: "Fecha para verificar promociones (opcional, default: hoy)"
      required: ["workspace_id"]
      additionalProperties: false
    requires_slots: []
    scopes: ["read"]
    tier_required: "basic"
    rate_limit_per_min: 60
    cost_tokens: 50
    timeout_ms: 3000

  - name: "get_business_hours"
    description: |
      Consulta el horario de atención del negocio.
      Devuelve horarios por día de la semana y días especiales.
      Úsalo cuando el cliente pregunte por horarios de apertura.
    args_schema:
      type: object
      properties:
        workspace_id:
          type: string
          description: "ID del workspace (requerido por MCP)"
      required: ["workspace_id"]
      additionalProperties: false
    requires_slots: []
    scopes: ["read"]
    tier_required: "basic"
    rate_limit_per_min: 60
    cost_tokens: 50
    timeout_ms: 3000

  # ==========================================
  # WRITE TOOLS - Acciones de reserva
  # ==========================================

  - name: "book_appointment"
    description: |
      Confirma y reserva un turno para un servicio específico.
      Requiere todos los datos del cliente y horario deseado.
      IMPORTANTE: Llamar solo DESPUÉS de verificar disponibilidad con check_service_availability.
    args_schema:
      type: object
      properties:
        workspace_id:
          type: string
          description: "ID del workspace (requerido por MCP)"
        service_type:
          type: string
          description: "Nombre del servicio (ej: 'Corte de Cabello')"
        preferred_date:
          type: string
          format: date
          description: "Fecha deseada en formato YYYY-MM-DD"
        preferred_time:
          type: string
          description: "Hora deseada en formato HH:MM"
        client_name:
          type: string
          description: "Nombre completo del cliente"
        client_email:
          type: string
          format: email
          description: "Email del cliente"
        client_phone:
          type: string
          description: "Teléfono del cliente (opcional)"
        staff_id:
          type: string
          description: "ID del profesional preferido (opcional)"
        notes:
          type: string
          description: "Notas adicionales (opcional)"
      required: ["workspace_id", "service_type", "preferred_date", "preferred_time", "client_name", "client_email"]
      additionalProperties: false
    requires_slots: ["service_type", "preferred_date", "preferred_time", "client_name", "client_email"]
    scopes: ["write"]
    tier_required: "basic"
    rate_limit_per_min: 10
    cost_tokens: 200
    timeout_ms: 10000
