version: "3.9"

services:
  tika:
    image: apache/tika:2.9.2.0-full
    container_name: pulpo-tika
    ports:
      - "9998:9998"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx2g
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9998/tika"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - pulpo-network

  # Servicio de ingesta de archivos
  file-ingestor:
    build:
      context: .
      dockerfile: Dockerfile.file-ingestor
    container_name: pulpo-file-ingestor
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://pulpo_user:pulpo_password@postgres:5432/pulpo_db
      - TIKA_URL=http://tika:9998/tika
      - OLLAMA_URL=http://ollama:11434
      - EMBEDDING_MODEL=nomic-embed-text
      - EMBEDDING_DIMS=768
      - SERVER_ADDR=:8080
      - READ_LOCAL_FILES=true
    depends_on:
      - tika
      - postgres
      - ollama
    restart: unless-stopped
    networks:
      - pulpo-network
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs

networks:
  pulpo-network:
    external: true

